### ISSUE TITLE
It appears to fail on sandboxes frames without `allow-scripts`

### ISSUE THREAD

**Issue by fregante** [awesome-webextension/webpack-target-webextension#41]
I'm still looking into it, but it seems that the first chunk runs correctly, but then anything `import()`'d fails with this error:

```
contentScript.js:18475 Uncaught (in promise) ChunkLoadError: Loading chunk vendors-node_modules_emotion_react_dist_emotion-react_browser_esm_js failed.
(undefined: undefined)
    at __webpack_require__.f.j (contentScript.js:18475:29)
    at contentScript.js:18249:40
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (contentScript.js:18248:67)
    at initContentScript (contentScript.js:18610:229)
    at contentScript.js:18630:10
    at contentScript.js:18638:3
    at contentScript.js:18640:12
```

It looks like `import` works fine though, I can run this in the console for that frame:

```js
const code = 'export const foo = 123'
const imported = await import(`data:text/javascript;charset=utf-8,${encodeURIComponent(code)}`)
console.log(imported.foo) // Should print 123
```

**Comment by fregante** [comment]
The repro should look something like:

```html
<html>
<body>
  <iframe srcdoc="<p>Hello world!</p>" sandbox>
</body>
</html>
```

```js
console.log('contentscript.js')
import('./secondary.js')
```
```js
console.log('secondary.js')
```

**Comment by fregante** [comment]
Thank you! By the way this is the actual error produced:


<img width="903" alt="image" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/7f23fa2c-e162-43f8-8e20-7f4984aa1270">

It seems that the modules are loaded, but they are not registered in the global chunk list, so after the `import()` is completed, the chunk can't be found on that line.

Does the chunk loader inject `script` tags in order to work? Even after using `import()` to load them? Because that's how the content script might end up running in the "unsafe world" and be blocked.

**Comment by Jack-Works** [comment]
@fregante according to the error message, the execution failed because the "document's frame is sandboxed and the 'allow-scripts' permission is not set."

did you try `<iframe sandbox="allow-scripts" ...`?

**Comment by fregante** [comment]
The point is that the script *is* running, regardless of the sandbox, because that error comes from webpack. The main chunk runs, the imports don't. Imports should run too, as shown in the `import()` example

**Comment by Jack-Works** [comment]
hello, I found it is a Chrome bug. See https://bugs.chromium.org/p/chromium/issues/detail?id=816121 and please state your use case to let it fixed.

I'll try to make a workaround.

**Comment by Jack-Works** [comment]
@fregante plz try this https://github.com/awesome-webextension/webpack-target-webextension/pull/42

**Comment by fregante** [comment]
I found a way via `fetch`:

```js
async function init() {
  console.log('Hello from content script')
  const inner = await fetch(chrome.runtime.getURL('./inner.js'))
  const innerText = await res.text()
  import(`data:text/javascript;charset=utf-8,${encodeURIComponent(innerText)}`).then(console.log)
}

init()
```
```js
// inner.js
export const foo = 123;
console.log('Hello from inner script')
```

<img width="433" alt="Screenshot" src="https://github.com/awesome-webextension/webpack-target-webextension/assets/1402241/cac873d3-0124-4d43-b333-e8aadceaaabb">

**Comment by fregante** [comment]
Edit: but that's gonna break sourcemaps so it's a bad solution to this.

**Comment by fregante** [comment]
> hello, I found it is a Chrome bug. See https://bugs.chromium.org/p/chromium/issues/detail?id=816121 and please state your use case to let it fixed.

I don’t think that's quite the same issue, although it's certainly related. The issue mentions loading HTML pages in a `<iframe sandbox>` rather than content scripts and `import()` specifically. It's a different context entirely: "main world on extension page" vs "isolated world on web page"

**Comment by Jack-Works** [comment]
hi, 1.1.1 has been released @fregante 

https://github.com/awesome-webextension/webpack-target-webextension/blob/master/CHANGELOG.md#111
